=== robbyn/sketchwalk/src/main/resources/com/sketchwalk/jedo/jedo.dtd
<?xml version="1.0" encoding="UTF-8"?>
<!ELEMENT mapping (class*)>
<!ATTLIST mapping package CDATA #IMPLIED>

<!ELEMENT class (id?,(field|component|reference|set|list|map)*,
        load?,query*,insert?,update?,delete?,statement*)>
<!ATTLIST class name CDATA #REQUIRED>

<!ELEMENT id (field+)>

<!ELEMENT field EMPTY>
<!ATTLIST field
    name CDATA #REQUIRED
    column CDATA #IMPLIED
>

<!ELEMENT component (field+)>
<!ATTLIST component name CDATA #REQUIRED>

<!ELEMENT reference EMPTY>
<!ATTLIST reference
    name CDATA #REQUIRED
    column CDATA #REQUIRED
    fetch-mode (eager|lazy) #IMPLIED
>

<!ELEMENT set (element?,(fetch|clear|add|remove)*)>
<!ATTLIST set
    name CDATA #REQUIRED
    fetch-mode (eager|lazy) #IMPLIED
    order CDATA #IMPLIED
>

<!ELEMENT list (element?,(fetch|clear|add|remove|set-at|add-at|remove-at)*)>
<!ATTLIST list
    name CDATA #REQUIRED
    fetch-mode (eager|lazy) #IMPLIED
>

<!ELEMENT map (key,element?,(fetch|clear|put|remove-key)*)>
<!ATTLIST map
    name CDATA #REQUIRED
    fetch-mode (eager|lazy) #IMPLIED
>

<!ELEMENT key EMPTY>
<!ATTLIST key
    type CDATA #IMPLIED
    column CDATA #REQUIRED
>

<!ELEMENT element EMPTY>
<!ATTLIST element
    type CDATA #IMPLIED
    column CDATA #REQUIRED
>

<!ELEMENT load (#PCDATA)>

<!ELEMENT query (#PCDATA)>
<!ATTLIST query
    name CDATA #REQUIRED
    parameters CDATA #IMPLIED
>

<!ELEMENT insert (#PCDATA)>
<!ATTLIST insert get-generated-keys (true|false) #IMPLIED>

<!ELEMENT update (#PCDATA)>

<!ELEMENT delete (#PCDATA)>

<!ELEMENT statement (#PCDATA)>
<!ATTLIST statement
    name CDATA #REQUIRED
    parameters CDATA #IMPLIED
>

<!-- Collection queries -->

<!ELEMENT fetch (#PCDATA)>
<!ATTLIST fetch
    parent CDATA "parent"
>
<!ELEMENT clear (#PCDATA)>
<!ATTLIST clear
    parent CDATA "parent"
>
<!ELEMENT add (#PCDATA)>
<!ATTLIST add
    parent CDATA "parent"
    element CDATA "element"
>
<!ELEMENT remove (#PCDATA)>
<!ATTLIST remove
    parent CDATA "parent"
    element CDATA "element"
>

<!-- List queries -->

<!ELEMENT set-at (#PCDATA)>
<!ATTLIST set-at
    parent CDATA "parent"
    element CDATA "element"
    index CDATA "index"
>
<!ELEMENT add-at (#PCDATA)>
<!ATTLIST add-at
    parent CDATA "parent"
    element CDATA "element"
    index CDATA "index"
>
<!ELEMENT remove-at (#PCDATA)>
<!ATTLIST remove-at
    parent CDATA "parent"
    index CDATA "index"
>

<!-- Map queries -->

<!ELEMENT put (#PCDATA)>
<!ATTLIST put
    parent CDATA "parent"
    element CDATA "element"
    key CDATA "key"
>

<!ELEMENT remove-key (#PCDATA)>
<!ATTLIST remove-key
    parent CDATA "parent"
    key CDATA "key"
>

=== robbyn/sketchwalk/src/main/resources/com/sketchwalk/jedo/mapping.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE mapping PUBLIC '-//tastefuljava.org//Jedo Mapping File 1.0//EN' 'jedo.dtd'>
<mapping package="org.tastefuljava.jedo.testdb">
    <class name="Folder">
        <id>
            <field name="id" column="ID"/>
        </id>
        <reference name="parent" column="PARENT_ID" fetch-mode="lazy"/>
        <field name="name" column="NAME"/>
        <set name="subfolders" fetch-mode="lazy" order="name">
            <fetch>
                SELECT * FROM folders
                WHERE PARENT_ID=${id}
            </fetch>
            <add parent="parent" element="child">
                UPDATE folders
                SET PARENT_ID=${parent.id}
                WHERE ID=${id}
            </add>
            <remove parent="parent" element="child">
                UPDATE folders
                SET PARENT_ID=NULL
                WHERE PARENT_ID=${parent.id} AND ID=${id}
            </remove>
            <clear parent="parent">
                DELETE FROM folders
                WHERE FOLDER_ID=${id}
            </clear>
        </set>
        <set name="pictures" fetch-mode="lazy" order="name">
            <fetch parent="folder">
                SELECT * FROM pictures
                WHERE FOLDER_ID=${id}
            </fetch>
            <add parent="folder" element="picture">
                UPDATE pictures
                SET FOLDER_ID=${folder.id}
                WHERE ID=${id}
            </add>
            <remove parent="folder" element="picture">
                DELETE FROM pictures
                WHERE FOLDER_ID=${folder.id} AND ID=${id}
            </remove>
            <clear parent="folder">
                DELETE FROM pictures
                WHERE FOLDER_ID=${id}
            </clear>
        </set>

        <load>
            SELECT * FROM folders
            WHERE ID=${id}
        </load>
        <query name="rootFolder" parameters="name">
            SELECT * FROM folders
            WHERE PARENT_ID IS NULL
                AND NAME=${name}
        </query>
        <query name="subfolder" parameters="parent,name">
            SELECT * FROM folders
            WHERE PARENT_ID=${parent.id}
                AND NAME=${name}
        </query>
        <insert get-generated-keys="true">
            INSERT INTO folders(PARENT_ID,NAME) VALUES(${parent.id},${name})
        </insert>
    </class>

    <class name="Picture">
        <id>
            <field name="id" column="ID"/>
        </id>
        <reference name="folder" column="FOLDER_ID"/>
        <field name="name" column="NAME"/>
        <field name="timestamp" column="TIMESTAMP"/>
        <field name="width" column="WIDTH"/>
        <field name="height" column="HEIGHT"/>
        <component name="gpsData">
            <field name="latitude" column="LATITUDE"/>
            <field name="longitude" column="LONGITUDE"/>
            <field name="altitude" column="ALTITUDE"/>
        </component>
        <list name="tags" fetch-mode="eager">
            <element column="NAME"/>
            <fetch>
                SELECT * FROM picture_tags
                WHERE PICTURE_ID=${id}
                ORDER BY PICTURE_ID,INDEX
            </fetch>
            <add-at parent="picture" element="tag" index="index">
                INSERT INTO picture_tags(PICTURE_ID,INDEX,NAME)
                VALUES(${picture.id},${index},${tag})
            </add-at>
            <clear parent="picture">
                DELETE FROM picture_tags
                WHERE PICTURE_ID=${id}
            </clear>
        </list>
        <map name="descriptions" fetch-mode="lazy">
            <key column="LANGUAGE"/>
            <element column="DESCRIPTION"/>
            <fetch>
                SELECT * FROM picture_descriptions
                WHERE PICTURE_ID=${id}
            </fetch>
            <put parent="picture" key="language" element="description">
                INSERT INTO picture_descriptions(PICTURE_ID,LANGUAGE,DESCRIPTION)
                VALUES(${picture.id},${language},${description})
            </put>
            <remove-key parent="picture" key="language">
                DELETE FROM picture_tags
                WHERE PICTURE_ID=${id} AND LANGUAGE=${language}
            </remove-key>
            <clear parent="picture_descriptions">
                DELETE FROM picture_tags
                WHERE PICTURE_ID=${id}
            </clear>
        </map>

        <load>
            SELECT * FROM pictures
            WHERE ID=${id}
        </load>
        <query name="byName" parameters="folder,name">
            SELECT * FROM pictures
            WHERE FOLDER_ID=${folder.id}
                AND NAME=${name}
        </query>
        <insert get-generated-keys="true">
            INSERT INTO pictures(FOLDER_ID,NAME,TIMESTAMP,WIDTH,HEIGHT,LATITUDE,
                LONGITUDE,ALTITUDE)
            VALUES(${folder.id},${name},${timestamp:TIMESTAMP},${width},
                ${height},${gpsData.latitude},${gpsData.longitude},
                ${gpsData.altitude})
        </insert>
        <update>
            UPDATE pictures SET FOLDER_ID=${folder.id},NAME=${name},
                TIMESTAMP=${timestamp:TIMESTAMP},WIDTH=${width},
                HEIGHT=${height},LATITUDE=${gpsData.latitude},
                LONGITUDE=${gpsData.longitude},
                ALTITUDE=${gpsData.altitude}
            WHERE ID=${id}
        </update>
        <delete>
            DELETE FROM pictures WHERE ID=${id}
        </delete>
    </class>
</mapping>

=== robbyn/sketchwalk/src/test/resources/com/sketchwalk/biz/mapping-h2.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE mapping PUBLIC '-//tastefuljava.org//Jedo Mapping File 1.0//EN' 'jedo.dtd'>
<mapping package="com.sketchwalk.biz">
    <class name="Media">
        <id>
            <field name="id" column="ID"/>
        </id>
        <field name="mimeType" column="MIME_TYPE"/>
        <field name="data" column="DATA"/>
        <load>
            SELECT * FROM medias
            WHERE ID=${id}
        </load>
        <insert get-generated-keys="true">
            INSERT INTO medias(MIME_TYPE,DATA)
            VALUES(${mimeType},${data})
        </insert>
        <delete>
            DELETE FROM medias WHERE ID=${id}
        </delete>
    </class>

    <class name="User">
        <id>
            <field name="id" column="ID"/>
        </id>
        <field name="username" column="USERNAME"/>
        <field name="email" column="EMAIL"/>
        <field name="passwordHash" column="PASSWORD_HASH"/>
        <field name="displayName" column="DISPLAY_NAME"/>
        <reference name="profilePicture" column="PROFILE_PICTURE" fetch-mode="lazy"/>
        <reference name="coverPicture" column="COVER_PICTURE" fetch-mode="lazy"/>
        <set name="groups" fetch-mode="lazy">
            <fetch>
                SELECT groups.* FROM groups_users,groups
                WHERE USER_ID=${id} AND GROUP_ID=groups.ID
            </fetch>
            <add parent="parent" element="child">
                INSERT INTO groups_users(GROUP_ID,USER_ID)
                VALUES(${child.id},${parent.id})
            </add>
            <remove parent="parent" element="child">
                DELETE FROM groups_users
                WHERE USER_ID=${parent.id} AND GROUP_ID=${child.id}
            </remove>
            <clear parent="parent">
                DELETE FROM groups_users
                WHERE USER_ID=${parent.id}
            </clear>
        </set>

        <load>
            SELECT * FROM users
            WHERE ID=${id}
        </load>
        <query name="byUsername" parameters="username">
            SELECT * FROM users
            WHERE USERNAME=${username}
        </query>
        <query name="byEmail" parameters="email">
            SELECT * FROM users
            WHERE EMAIL=${email}
        </query>
        <insert get-generated-keys="true">
            INSERT INTO users(USERNAME,EMAIL,PASSWORD_HASH,DISPLAY_NAME,PROFILE_PICTURE,COVER_PICTURE)
            VALUES(${username},${email},${passwordHash},${displayName},${profilePicture.id},${coverPicture.id})
        </insert>
        <update>
            UPDATE users
            SET USERNAME=${username}, EMAIL=${email}, PASSWORD_HASH=${passwordHash},
                DISPLAY_NAME=${displayName}, PROFILE_PICTURE=${profilePicture.id}, COVER_PICTURE=${coverPicture.id}
            WHERE ID=${id}
        </update>
        <delete>
            DELETE FROM users WHERE ID=${id}
        </delete>
    </class>

    <class name="Group">
        <id>
            <field name="id" column="ID"/>
        </id>
        <field name="name" column="NAME"/>
        <field name="displayName" column="DISPLAY_NAME"/>
        <field name="description" column="DESCRIPTION"/>
        <set name="users" fetch-mode="lazy">
            <fetch>
                SELECT users.* FROM groups_users,users
                WHERE GROUP_ID=${id} AND USER_ID=users.ID
            </fetch>
            <add parent="parent" element="child">
                INSERT INTO groups_users(GROUP_ID,USER_ID)
                VALUES(${parent.id},${child.id})
            </add>
            <remove parent="parent" element="child">
                DELETE FROM groups_users
                WHERE GROUP_ID=${parent.id} AND USER_ID=${child.id}
            </remove>
            <clear parent="parent">
                DELETE FROM groups_users
                WHERE GROUP_ID=${parent.id}
            </clear>
        </set>

        <load>
            SELECT * FROM groups
            WHERE ID=${id}
        </load>
        <query name="byName" parameters="name">
            SELECT * FROM groups
            WHERE USERNAME=${name}
        </query>
        <insert get-generated-keys="true">
            INSERT INTO groups(NAME,DISPLAY_NAME,DESCRIPTION)
            VALUES(${name},${displayName},${description})
        </insert>
        <update>
            UPDATE groups
            SET NAME=${name}, DISPLAY_NAME=${displayName},
                DESCRIPTION=${description}
            WHERE ID=${id}
        </update>
        <delete>
            DELETE FROM groups WHERE ID=${id}
        </delete>
    </class>
</mapping>

=== robbyn/sketchwalk/src/test/resources/com/sketchwalk/biz/mapping.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE mapping PUBLIC '-//tastefuljava.org//Jedo Mapping File 1.0//EN' 'jedo.dtd'>
<mapping package="com.sketchwalk.biz">
    <class name="User">
        <id>
            <field name="id" column="ID"/>
        </id>
        <field name="username" column="USERNAME"/>
        <field name="email" column="EMAIL"/>
        <field name="displayName" column="DISPLAY_NAME"/>
        <set name="groups" fetch-mode="lazy">
            <fetch>
                SELECT groups.* FROM groups_users,groups
                WHERE USER_ID=${id} AND GROUP_ID=groups.ID
            </fetch>
            <add parent="parent" element="child">
                INSERT INTO groups_users(GROUP_ID,USER_ID)
                VALUES(${child.id},${parent.id})
            </add>
            <remove parent="parent" element="child">
                DELETE FROM groups_users
                WHERE USER_ID=${parent.id} AND GROUP_ID=${child.id}
            </remove>
            <clear parent="parent">
                DELETE FROM groups_users
                WHERE USER_ID=${parent.id}
            </clear>
        </set>

        <load>
            SELECT * FROM users
            WHERE ID=${id}
        </load>
        <query name="byUsername" parameters="username">
            SELECT * FROM users
            WHERE USERNAME=${username}
        </query>
        <query name="byEmail" parameters="email">
            SELECT * FROM users
            WHERE EMAIL=${email}
        </query>
        <insert get-generated-keys="true">
            INSERT INTO users(USERNAME,EMAIL,DISPLAY_NAME)
            VALUES(${username},${email},${displayName})
        </insert>
        <update>
            UPDATE users
            SET USERNAME=${username}, EMAIL=${email}, DISPLAY_NAME=${displayName}
            WHERE ID=${id}
        </update>
        <delete>
            DELETE FROM users WHERE ID=${id}
        </delete>
    </class>

    <class name="Group">
        <id>
            <field name="id" column="ID"/>
        </id>
        <field name="name" column="NAME"/>
        <field name="displayName" column="DISPLAY_NAME"/>
        <field name="description" column="DESCRIPTION"/>
        <set name="users" fetch-mode="lazy">
            <fetch>
                SELECT users.* FROM groups_users,users
                WHERE GROUP_ID=${id} AND USER_ID=users.ID
            </fetch>
            <add parent="parent" element="child">
                INSERT INTO groups_users(GROUP_ID,USER_ID)
                VALUES(${parent.id},${child.id})
            </add>
            <remove parent="parent" element="child">
                DELETE FROM groups_users
                WHERE GROUP_ID=${parent.id} AND USER_ID=${child.id}
            </remove>
            <clear parent="parent">
                DELETE FROM groups_users
                WHERE GROUP_ID=${parent.id}
            </clear>
        </set>

        <load>
            SELECT * FROM groups
            WHERE ID=${id}
        </load>
        <query name="byName" parameters="name">
            SELECT * FROM groups
            WHERE USERNAME=${name}
        </query>
        <insert get-generated-keys="true">
            INSERT INTO groups(NAME,DISPLAY_NAME,DESCRIPTION)
            VALUES(${name},${displayName},${description})
        </insert>
        <update>
            UPDATE groups
            SET NAME=${name}, DISPLAY_NAME=${displayName},
                DESCRIPTION=${description}
            WHERE ID=${id}
        </update>
        <delete>
            DELETE FROM groups WHERE ID=${id}
        </delete>
    </class>
</mapping>
